name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  # EDIT ME
  # `createEnv.sh` sends a dispatch request to test-instance to create a new on-demand environment.
  # The payload of the request needs to include a property telling test-instance which branch to use for this project.
  # This variable indicates the NAME of that property. The VALUE (branch name) is automatically retrieved.
  BRANCH_KEY: webBranch
jobs:
  create-on-demand-env:
    name: Create On Demand Env for E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: ./on-demand-testing-workflows/e2e_tests.setup.yml
        with:
          branch-key: $BRANCH_KEY
    
  run-e2e-tests:
    name: Run E2E Tests
    needs: create-on-demand-env
    runs-on:
      group: qa_aws_runners
    defaults:
      run:
        working-directory: swipesimpleweb-playwright-automation/tests
    timeout-minutes: 90
    env:
      # EDIT ME
      # Environment variables needed by your e2e tests can be defined here.
      webEnvBaseUrl: "pr${{ github.event.number }}.swipesimpleqa.com"
      GH_API_TOKEN: ${{ secrets.GH_TOKEN_ACCESS_PLAYWRIGHT }}
    steps:
      - name: Checkout E2E Tests
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # EDIT ME
          # If only specific folders are needed for your e2e tests, you can speed up the checkout process by defining them here.
          sparse-checkout: swipesimpleweb-playwright-automation
          
      # EDIT ME
      # Enter the commands required to run your e2e tests.
      - name: Run SwipeSimple Web tests
        run: |
          source ~/.virtualenvs/e2eTests/bin/activate
          playwright install
          
          xvfb-run pytest --tracing=retain-on-failure --html=E2ETestResults.html --self-contained-html -m pr
        
      # EDIT ME
      # Update the path to any files output by your e2e tests.
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: AutomatedNightlyTestRun_FailureTraces
          path: |
            tests/E2ETestResults.html
            */test-results/*/trace.zip
          retention-days: 30
